---
version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run
          command: |
            mkdir -p keys
            echo ${DEVHUB_SERVER_KEY_BASE64} | base64 -d >> keys/server.key
            for username in `echo ${DEVHUB_POOL_USERNAMES} | sed "s/,/ /g"`
            do
              yarn -s sfdx force:auth:jwt:grant -i ${SF_CLIENT_ID} -f keys/server.key -u ${username}
            done
            yarn -s sfdx force:org:list
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
